//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavyClient.RoutingSoapProxy {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteResult", Namespace="http://schemas.datacontract.org/2004/07/RoutingServiceLib")]
    [System.SerializableAttribute()]
    public partial class RouteResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private HeavyClient.RoutingSoapProxy.RouteLeg[] legsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string modeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string noteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalDistanceMetersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double totalDurationSecondsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public HeavyClient.RoutingSoapProxy.RouteLeg[] legs {
            get {
                return this.legsField;
            }
            set {
                if ((object.ReferenceEquals(this.legsField, value) != true)) {
                    this.legsField = value;
                    this.RaisePropertyChanged("legs");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mode {
            get {
                return this.modeField;
            }
            set {
                if ((object.ReferenceEquals(this.modeField, value) != true)) {
                    this.modeField = value;
                    this.RaisePropertyChanged("mode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string note {
            get {
                return this.noteField;
            }
            set {
                if ((object.ReferenceEquals(this.noteField, value) != true)) {
                    this.noteField = value;
                    this.RaisePropertyChanged("note");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double totalDistanceMeters {
            get {
                return this.totalDistanceMetersField;
            }
            set {
                if ((this.totalDistanceMetersField.Equals(value) != true)) {
                    this.totalDistanceMetersField = value;
                    this.RaisePropertyChanged("totalDistanceMeters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double totalDurationSeconds {
            get {
                return this.totalDurationSecondsField;
            }
            set {
                if ((this.totalDurationSecondsField.Equals(value) != true)) {
                    this.totalDurationSecondsField = value;
                    this.RaisePropertyChanged("totalDurationSeconds");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteLeg", Namespace="http://schemas.datacontract.org/2004/07/RoutingServiceLib")]
    [System.SerializableAttribute()]
    public partial class RouteLeg : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double distanceMetersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double durationSecondsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double[][] geometryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] instructionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double distanceMeters {
            get {
                return this.distanceMetersField;
            }
            set {
                if ((this.distanceMetersField.Equals(value) != true)) {
                    this.distanceMetersField = value;
                    this.RaisePropertyChanged("distanceMeters");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double durationSeconds {
            get {
                return this.durationSecondsField;
            }
            set {
                if ((this.durationSecondsField.Equals(value) != true)) {
                    this.durationSecondsField = value;
                    this.RaisePropertyChanged("durationSeconds");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double[][] geometry {
            get {
                return this.geometryField;
            }
            set {
                if ((object.ReferenceEquals(this.geometryField, value) != true)) {
                    this.geometryField = value;
                    this.RaisePropertyChanged("geometry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] instructions {
            get {
                return this.instructionsField;
            }
            set {
                if ((object.ReferenceEquals(this.instructionsField, value) != true)) {
                    this.instructionsField = value;
                    this.RaisePropertyChanged("instructions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoutingSoapProxy.IRoutingServiceSoap")]
    public interface IRoutingServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingServiceSoap/GetRoute", ReplyAction="http://tempuri.org/IRoutingServiceSoap/GetRouteResponse")]
        HeavyClient.RoutingSoapProxy.RouteResult GetRoute(string from, string to);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingServiceSoap/GetRoute", ReplyAction="http://tempuri.org/IRoutingServiceSoap/GetRouteResponse")]
        System.Threading.Tasks.Task<HeavyClient.RoutingSoapProxy.RouteResult> GetRouteAsync(string from, string to);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoutingServiceSoapChannel : HeavyClient.RoutingSoapProxy.IRoutingServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutingServiceSoapClient : System.ServiceModel.ClientBase<HeavyClient.RoutingSoapProxy.IRoutingServiceSoap>, HeavyClient.RoutingSoapProxy.IRoutingServiceSoap {
        
        public RoutingServiceSoapClient() {
        }
        
        public RoutingServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutingServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public HeavyClient.RoutingSoapProxy.RouteResult GetRoute(string from, string to) {
            return base.Channel.GetRoute(from, to);
        }
        
        public System.Threading.Tasks.Task<HeavyClient.RoutingSoapProxy.RouteResult> GetRouteAsync(string from, string to) {
            return base.Channel.GetRouteAsync(from, to);
        }
    }
}
